# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/platecrop.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import types_pb2 as protos_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/platecrop.proto\x12\x1fVehicleIdentification.PlateCrop\x1a\x12protos/types.proto2[\n\tPlateCrop\x12N\n\x04\x43rop\x12\".VehicleIdentification.Types.Image\x1a\".VehicleIdentification.Types.Image')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.platecrop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLATECROP']._serialized_start=79
  _globals['_PLATECROP']._serialized_end=170
# @@protoc_insertion_point(module_scope)
