# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/yolov8.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import types_pb2 as protos_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/yolov8.proto\x12\x1cVehicleIdentification.Yolov8\x1a\x12protos/types.proto2a\n\x06Yolov8\x12W\n\x06\x44\x65tect\x12\".VehicleIdentification.Types.Image\x1a).VehicleIdentification.Types.DetectResult')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.yolov8_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YOLOV8']._serialized_start=73
  _globals['_YOLOV8']._serialized_end=170
# @@protoc_insertion_point(module_scope)
